version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"

  api1: &api
    image: matheuspieropan/rinhabackend2025:final
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "120M"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "120M"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: "0.45"
#          memory: "90M"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true