version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api1: &api
    image: matheuspieropan/rinhabackend2025:graalvm
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true